// Shared types for the signal engine and backtester.
// All time series are arrays sorted ascending by date.

export type Bar = {
  /** ISO date string for the trading bar (yyyy mm dd). */
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  /** Adjusted close, or close if the data source did not split adjust. */
  adjClose: number;
  volume: number;
};

export type StrategyId = "rsi_mean_reversion" | "ma_crossover" | "bollinger_breakout";

export type Side = "long" | "flat";

export type Signal = {
  /** Signal index in the OHLC array (i.e. signals[k] aligns to bars[k]). */
  index: number;
  /** What the strategy thinks the position should be after this bar closes. */
  target: Side;
  /** Optional human readable reason. */
  reason?: string;
};

export type Trade = {
  entryDate: string;
  entryPrice: number;
  exitDate: string;
  exitPrice: number;
  /** Shares held during the trade. Always a positive number for long trades. */
  shares: number;
  /** Dollar PnL after the trade closes. */
  pnl: number;
  /** Percentage return on the position notional at entry. */
  returnPct: number;
  /** Bars held including entry and exit. */
  barsHeld: number;
};

export type EquityPoint = {
  date: string;
  equity: number;
  /** Drawdown at this bar, expressed as a non positive number (0 means at peak). */
  drawdown: number;
};

export type BacktestStats = {
  startDate: string;
  endDate: string;
  startingCapital: number;
  endingEquity: number;
  totalReturnPct: number;
  annualizedReturnPct: number;
  sharpe: number;
  maxDrawdownPct: number;
  winRatePct: number;
  trades: number;
  avgWinPct: number;
  avgLossPct: number;
  longestLosingStreak: number;
  buyHoldReturnPct: number;
  buyHoldAnnualizedPct: number;
};

export type BacktestResult = {
  symbol: string;
  strategy: StrategyId;
  params: Record<string, number>;
  stats: BacktestStats;
  equity: EquityPoint[];
  trades: Trade[];
  /** Bar by bar signal target, parallel to the OHLC bars used. */
  signals: Side[];
  bars: Bar[];
};

export type AICommentary = {
  paragraph: string;
  /** True when generated by the model, false when the deterministic fallback wrote it. */
  fromModel: boolean;
};
